server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    org:
      atmosphere: warn

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,transcribe

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vaadinstart
    username: vaadinstart
    password: vaadinstart
  jpa:
    defer-datasource-initialization: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB

gcloud:
  project-id: ${GCLOUD_PROJECT_ID}
  private-key: ${GCLOUD_KEY}
  bucket-name: ${GCLOUD_BUCKET_NAME}
  speech-endpoint: 'europe-west4-speech.googleapis.com:443'
  location: 'europe-west4'

youtube-dl:
  execution-path: ${YOUTUBE_DL_EXECUTION_PATH}

yt-dlp:
  execution-path: ${YT_DLP_EXECUTION_PATH}

ffmpeg:
  ffmpeg-execution-path: ${FFMPEG_EXECUTION_PATH}
  ffprobe-execution-path: ${FFPROBE_EXECUTION_PATH}