server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    transcribe: trace

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin,transcribe
  async-supported: true
  frontend:
    hotdeploy: true

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/transcribe?reWriteBatchedInserts=true
    username: transcribe
    password: transcribe
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 10000
  jpa:
    open-in-view: false
    defer-datasource-initialization: false
    properties:
      hibernate:
        query:
          fail_on_pagination_over_collection_fetch: true
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 30
        default_batch_fetch_size: 30
        show_sql: false
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: utf-8
    check-template-location: true

gcloud:
  project-id: 'transcribe-dev-444319'
  bucket-name: 'transcribe-dev-cloud-storage'
  temp-bucket-name: 'transcribe-dev-temp-cloud-storage'
  speech-endpoint: 'europe-west4-speech.googleapis.com:443'
  ai-platform-endpoint: 'europe-west4-aiplatform.googleapis.com:443'
  location: 'europe-west4'
  private-key: ${GCLOUD_KEY}

openai:
  api-key: ${OPENAI_API_KEY}

yt-dlp:
  execution-path: ${YT_DLP_EXECUTION_PATH}

ffmpeg:
  ffmpeg-execution-path: ${FFMPEG_EXECUTION_PATH}
  ffprobe-execution-path: ${FFPROBE_EXECUTION_PATH}

pyannote:
  api-key: ${PYANNOTE_API_KEY}
  base-url: 'https://api.pyannote.ai/v1'